### ISSUE TITLE
Indirizzo di spedizione emails

### ISSUE THREAD

**Issue by oniram88** [oniram88/RunnersBikers#1]
le emails partono dal mio indirizzo, cambiare in quello di runnersbikers@gmail.com

fai generare una password a fabio

**Comment by fbarnaba** [comment]
la password per accedere alla casella di posta runnersbikers@gmail.com è fabio1972 puoi usare questa

**Comment by oniram88** [comment]
ti ho cancellato il commento perchè conteneva la password in chiaro.
generami una password specifica per l'app dall'interno dell'area amministrativa del tuo account di google
