### ISSUE TITLE
accesso consolle controllo competizione (arbitri)

### ISSUE THREAD

**Issue by ghost** [oniram88/RunnersBikers#11]
probabilmente i tre arbitri saranno anche concorrenti, pertanto relativamente ai seguenti tre account 

•	Fabio Barnaba		 fbarnaba72@gmail.com
•	Fabio Sirigu                       fabiosirigu@gmail.com
•	Christian Rossanigo        christianrossanigo@outlook.com

è necessario assegnare anche i diritti da arbitro, o prevedevi di utilizzare altri tre account distinti per svolgere le funzioni da arbitro?

nel primo caso.

il mio accounta (fabio barnaba) esiste già.

puoi creare altri due account associati a fabio sirigu e christian rossanigo con rispettive password fabiosirigu e christianrossanigo assegnandogli anche i diritti da arbitro?

grazie

**Comment by oniram88** [comment]
ogni utente può essere sia utente che giudice, i ruoli li assegno io tramite terminale, in quanto non mi sembrava così necessario implementare anche un'interfaccia per definire chi è giudice, nel caso la si può aggiungere in futuro. per gli altri due account meglio che facciano il giro corretto, si iscrivono, confermano la mail e io gli assegno poi il ruolo di giudice
