### ISSUE TITLE
formato dei numeri inglese

### ISSUE THREAD

**Issue by ghost** [oniram88/RunnersBikers#12]
attenzione che in tutto il sito, il formato dei numeri è quello inglese con il . a delimitare gli interi dai decimali, dovremmo passare a quello italiano con la , a separare gli interi dai decimali.

questa banalità potrebbe rivelarsi un problema quando gli utenti inseriscono i numeri nel sito

grazie

**Comment by oniram88** [comment]
corretto nella versione 1.0.1
