### ISSUE TITLE
Implementazione emails

### ISSUE THREAD

**Issue by oniram88** [oniram88/RunnersBikers#15]

**Comment by oniram88** [comment]
- [x] INIZIO SFIDA
 

> SFIDATO
> 
> OGGETTO: TORNEO NEXT CHALLENGE PER RUNNER – SEI STATO SFIDATO
>  
> Caro <NOME E COGNOME>,
>  
> Brutte notizie per te: sei stato sfidato dal concorrente  <nome e cognome sfidante>
>  
> Avrai tempo sino al <giorno orario scadenza sfida> per EFFETTUARE E REGISTRARE sul sito ausiliario di gara la tua sessione.
>  
> Oltre tale limite, senza aver registrato alcuna sessione, perderai la sfida.
>  
> Non potrai sfidare nessun altro concorrente sino a quando la sfida corrente non sarà conclusa.
>  
> Il team

 
 
 

> 
> GIUDICI
>  
> OGGETTO: TORNEO NEXT CHALLENGE PER RUNNER – COMUNICAZIONE NUOVA SFIDA
>  
> Caro Arbitro <NOME E COGNOME>,
> ti comunichiamo che è stata lanciata una nuova sfida.
>  
> Il concorrente <nome e cognome sfidante> ha sfidato il concorrente <nome e cognome sfidato>.
>  
> I concorrenti avranno tempo sino al <giorno orario scadenza sfida> per EFFETTUARE E REGISTRARE sul sito ausiliario di gara le loro sessioni.
>  
> Il team
>  
>  
> SFIDANTE
>  
> OGGETTO: TORNEO NEXT CHALLENGE PER RUNNER – CONFERMA LANCIO SFIDA
>  
> Caro <NOME E COGNOME>,
>  
> TI confermiamo di avere registrato la sfida appena lanciata verso il concorrente <nome e cognome sfidante>.
>  
> Avrai tempo sino al <giorno orario scadenza sfida> per EFFETTUARE E REGISTRARE sul sito ausiliario di gara la tua sessione.
>  
> Oltre tale limite, senza aver registrato alcuna sessione, perderai la sfida.
>  
> Non potrai sfidare nessun altro concorrente sino a quando la sfida corrente non sarà conclusa.
>  
> Il team
>  
>  
>  

 
 
 
 
 
 
 

- [ ] REGISTRAZIONE

>  AL SITO AUSILIARIO DI GARA
>  
> OGGETTO: TORNEO NEXT CHALLENGE PER RUNNER – CONFERMA ISCRIZIONE AL SITO DEL TORNEO
>  
> Caro <NOME E COGNOME>,
>  
> Confermiamo l’avvenuta registrazione al sito del torneo Next Challenge per Runner.
>  
> Il link internet del sito è xxxxxxxxx
>  
> Le credenziali con cui potrai accedere al sito sono:
>  
> USERID =
>  
> PASSWORD =
>  
> Ti ricordiamo che DOVRAI registrare tutte le sessioni sportive valide ai fini della competizione non appena avrai realizzato la tua sessione.
>  
> Il team
>  

 
 
 
 
 
 
 
 
 
 

- [x] CONCLUSIONE SFIDA NEL CASO DI INSERIMENTO DI TUTTE E DUE LE SESSIONI PER TEMPO.
 
  

> GIUDICI non appena le due sessioni sono state registrate
>  
> OGGETTO: TORNEO NEXT CHALLENGE PER RUNNER – CONCLUSIONE SFIDA <COGNOME SFIDANTE> VS <COGNOME SFIDATO> CON DUE SESSIONI REGISTRATE
>  
> Caro Arbitro <NOME E COGNOME>,
> ti comunichiamo che si è appena conclusa una sfida con ENTRAMBE LE SESSIONI REGISTRATE.
>  
> Il concorrente <nome e cognome sfidante> ed il concorrente <nome e cognome sfidato> si sono sfidati.
>  
> Dovresti collegarti al sito xxxx per validare la sfida e decretare il vincitore.
>  
> Il team
>  
>  
> CONCORRENTI non appena le due sessioni sono state registrate
>  
> OGGETTO: TORNEO NEXT CHALLENGE PER RUNNER – CONCLUSIONE SFIDA <COGNOME SFIDANTE> VS <COGNOME SFIDATO>  CON DUE SESSIONI REGISTRATE
>  
> Caro <NOME E COGNOME>,
>  
> TI confermiamo di avere registrato entrambe le sessioni nella sfida  <nome e cognome sfidante> vs <nome e cognome sfidato>.
>  
> In queste ore gli arbitri valideranno le sessioni e determineranno i vincitori, riceverai una email non appena tutte le verifiche saranno completate.
>  
> Grazie per l’entusiasmo che dimostri partecipando al torneo,
>  
> il team
>  
>  
> CONCORRENTI dopo la verifica da parte dei giudici
>  
> OGGETTO: TORNEO NEXT CHALLENGE PER RUNNER – ESITO SFIDA <Cognome sfidante> vs <cognome sfidato>
>  
> Caro <NOME E COGNOME>,
>  
> ti comunichiamo che il vincitore della sfida nome e cognome sfidante> vs <nome e cognome sfidato> è <nome e cognome vincitore> che così si aggiudica i seguenti punti <zz>
>  
> le sessioni di sfida sono state:
>  
> < nome e cognome vincitore> < link sessione internet vincitore> < punti sessione vincitore>
>  
> < nome e cognome perdente> < link sessione internet perdente > < punti sessione perdente >
>  
> Da ora potete nuovamente sfidare un nuovo concorrente, secondo le regole del torneo.
>  
>  
> Grazie per l’entusiasmo che dimostri partecipando al torneo,
>  
> il team
>  
>  
> GIUDICI DOPO LA VERIFICA DA PARTE DEI GIUDICI
>  
> OGGETTO: TORNEO NEXT CHALLENGE PER RUNNER – SFIDA VALIDATA <Cognome sfidante> vs <cognome sfidato>
>  
> Caro Arbitro <NOME E COGNOME>,
> ti comunichiamo le sessioni di sfida tra i concorrenti <nome e cognome sfidante> ed il concorrente <nome e cognome sfidato> è stata appena effettuata.
>  
> Nessuna azione è più richiesta per tale sfida.
>  
> Il team
>  
>  

 
 
 

- [x] CONCLUSIONE SFIDA NEL CASO DI MANCATO INSERIMENTO DI UNA DELLE DUE SESSIONI NEL TEMPO MASSIMO PREVISTO PER LA SFIDA
 
 

> 
> GIUDICI non appena IL TEMPO è SCADUTO
>  
> OGGETTO: TORNEO NEXT CHALLENGE PER RUNNER – CONCLUSIONE SFIDA <COGNOME SFIDANTE> VS <COGNOME SFIDATO> CON UNA SOLA SESSIONE REGISTRATA
>  
> Caro Arbitro <NOME E COGNOME>,
> ti comunichiamo che si è appena concluso il tempo necessario a realizzare la sfida tra  <nome e cognome sfidante> ed il concorrente <nome e cognome sfidato>.
>  
> Uno dei due concorrenti non ha realizzato la propria sessione e pertanto la sfida è stata assegnata dal software.
>  
> Nessuna azione è più richiesta per tale sfida.
>  
> Il team
>  
>  
>  
> CONCORRENTI non appena IL TEMPO è SCADUTO
>  
> OGGETTO: TORNEO NEXT CHALLENGE PER RUNNER – ESITO SFIDA <Cognome sfidante> vs <cognome sfidato> CON UNA SOLA SESSIONE REGISTRATA
>  
> Caro <NOME E COGNOME>,
>  
> ti comunichiamo che il vincitore della sfida <nome e cognome sfidante> vs <nome e cognome sfidato> è <nome e cognome vincitore> che così si aggiudica i seguenti punti <zz>.
>  
> In tale sfida solo uno dei due concorrenti ha realizzato la propria sessione entro il tempo messo a disposizione per la sfida.
>  
> Pertanto l’unica sessione sportiva associata alla sfida è stata:
>  
> < nome e cognome vincitore> < link sessione internet vincitore> < punti sessione vincitore>
>  
> Da ora potete nuovamente sfidare un nuovo concorrente, secondo le regole del torneo.
>  
> Grazie per l’entusiasmo che dimostri partecipando al torneo,
>  
> il team
>  
>  

- [x] CONCLUSIONE SFIDA NEL CASO DI MANCATO INSERIMENTO DI ENTRAMBE LE SESSIONI DI GARA
 

> 
>  
> GIUDICI non appena IL TEMPO è SCADUTO
>  
> OGGETTO: TORNEO NEXT CHALLENGE PER RUNNER – CONCLUSIONE SFIDA <COGNOME SFIDANTE> VS <COGNOME SFIDATO> CON NESSUNA SESSIONE REGISTRATA
>  
> Caro Arbitro <NOME E COGNOME>,
> ti comunichiamo che si è appena concluso il tempo necessario a realizzare la sfida tra  <nome e cognome sfidante> ed il concorrente <nome e cognome sfidato>.
>  
> Nessuno dei due concorrenti ha realizzato la propria sessione e pertanto la sfida è stata annullata dal software.
>  
> Nessuna azione è più richiesta per tale sfida.
>  
> Il team
>  
>  
>  
> CONCORRENTI non appena IL TEMPO è SCADUTO
>  
> OGGETTO: TORNEO NEXT CHALLENGE PER RUNNER – CONCLUSIONE SFIDA <COGNOME SFIDANTE> VS <COGNOME SFIDATO> CON NESSUNA SESSIONE REGISTRATA
>  
> Caro <NOME E COGNOME>,
> ti comunichiamo che si è appena concluso il tempo necessario a realizzare la sfida tra  <nome e cognome sfidante> ed il concorrente <nome e cognome sfidato>.
>  
> Nessuno dei due concorrenti ha realizzato la propria sessione e pertanto la sfida è stata annullata.
>  
> Da ora potete nuovamente sfidare un nuovo concorrente, secondo le regole del torneo.
>  
> Il team

 
 
 

- [ ] ALLE 00.01 DEL GIORNO DAL QUALE è POSSIBILE LANCIARE LE SFIDE

>  
> GIUDICI E CONCORRENTI
>  
> OGGETTO: TORNEO NEXT CHALLENGE PER RUNNER – AVVIO SFIDE
>  
> Caro <NOME E COGNOME>,
> ti comunichiamo che da oggi e sino al giorno (data fine torneo  - 5 giorni) è possibile lanciare una sfida verso un concorrente che ha una posizione adiacente alla tua in graduatoria ( +/- 3 posizioni).
>  
> Per lanciare la sfida puoi collegarti al sito del torneo wwwzxx ed andare nel menù zzzxxx per scegliere un concorrente da sfidare, ammesso che tu abbia voglia di sfidare qualche altro concorrente.
>  
> Ricordiamo che avrai a disposizione 5 giorni dal lancio della sfida per realizzare la tua sessione sportiva, pertanto ti consigliamo di pianificare e lanciare la sfida nel momento che ritieni opportuno.
>  
> In bocca al lupo per le tue sfide, e mi raccomando l’importante non è vincere, ma allenarsi.
>  
> Il team
>  
>  
>  
>  
>  
> OKKIO AD IMPLEMENTARE IL VINCOLO CHE LE SFIDE DEVONO ESSERE LANCIATE ENTRO (data fine torneo  - 5 giorni – 2 ORE)

 
  

- [ ] ALLE 23.59 DELL’ULTIMO GIORNO DI TORNEO.
 

> 
> CONCORRENTI
>  
> OGGETTO: TORNEO NEXT CHALLENGE PER RUNNER – CONCLUSIONE TORNEO
>  
> Caro <NOME E COGNOME>,
> ti comunichiamo che si è appena concluso il torneo Next Challenge per Runner, non è più possibile registrare sessioni sportive.
>  
> In queste ore gli arbitri valideranno le sessioni e determineranno i vincitori, riceverete una una email non appena tutte le verifiche saranno completate.
>  
> Grazie per l’entusiasmo che avete dimostrato partecipando al torneo,
>  
> il team
>  

> GIUDICI
>  
>  
> OGGETTO: TORNEO NEXT CHALLENGE PER RUNNER – CONCLUSIONE TORNEO
>  
> Caro Arbitro NOME E COGNOME>,
> ti comunichiamo che si è appena concluso il torneo Next Challenge per Runner, non è più possibile registrare sessioni sportive.
>  
> In allegato il foglio excel con alcuni worksheet:
> Graduatoria formale
> Graduatoria su km percorsi
> Graduatoria su dislivello
> Graduatoria su tempo totale di sessioni
> Graduatoria su velocità media
> Statistiche: numero sessioni totali, km totali, dislivello totale, concorrente con più sessioni, concorrente con meno sessioni
>  
> Potrai procedere alla proclamazione dei vincitori
>  
> il team

**Comment by ghost** [comment]
quali email mancano da implementare?
