### ISSUE TITLE
aggiornamento punteggio

### ISSUE THREAD

**Issue by ghost** [oniram88/RunnersBikers#19]
ho effettuato un test, nel momento in cui elimino una sessione dalla lista sessioni, mi aspetto che il punteggio sia aggiornato di conseguenza.

nulla!

quindi ogni volta che vengono modificati i dati di una sessione / eliminata una sessione DEVE essere fatto il ricalcolo punteggio del concorrente.

grazie

**Comment by oniram88** [comment]
i punteggi si aggiornavano, a causa però dei vecchi punteggi con valori spropositati non venivano correttamente salvati, nella versione 1.0.4 correggo tutti i valori dei punteggi di test con il nuovo ricalcolo, e nel caso ci siano sfide con punti troppo alti(derivanti ancora dal vecchio sistema di calcolo) vengono troncati al nuovo 25%.
sono errori comunque dati dai dati di test
