### ISSUE TITLE
menù sfide con utenza NON arbitro

### ISSUE THREAD

**Issue by ghost** [oniram88/RunnersBikers#20]
ciao Marino,
sono entrato con uno degli utenti farlocchi (non arbitro) e selezionando il menù sfide non si vede nulla (pagina bianca).

non avevamo detto che dovevano comunque comparire tutte le sfide passate e correnti (senza dare la possibilità di modificare i contenuti)?

grazie
fabio

**Comment by oniram88** [comment]
Copy of #7

**Comment by oniram88** [comment]
V 1.0.6
