### ISSUE TITLE
problema con la sfida oniram e fbarnaba

### ISSUE THREAD

**Issue by ghost** [oniram88/RunnersBikers#22]
ieri oniram ha inserito una sessione

fbarnaba oggi ha inserito 3 sfide che NON vengono considerate ai fini della sfida.

non capisco perchè, alla luce delle sessioni di fbarnaba registrate oggi dovrebbe essere partita una email agli arbitri con la richiesta di validazione, invece nulla

grazie

**Comment by oniram88** [comment]
intendi di aver inserito 3 sessioni?

**Comment by ghost** [comment]
E non ne ha presa neanche una X la sfida

Il giorno dom 31 dic 2017 alle 11:16 Marino Bonetti <
notifications@github.com> ha scritto:

**Comment by oniram88** [comment]
legato al problema della issue #19 e dai vecchi punteggi.
V. 1.0.4

**Comment by oniram88** [comment]
riceverai anche le emails non inviate che identificano il cambio di stato delle sfide.
