### ISSUE TITLE
CALENDARIO DI GARA

### ISSUE THREAD

**Issue by ghost** [oniram88/RunnersBikers#26]
dopo aver completato i test, bisognà settare il calendario di gara corretto che è:
•	La gara inizia alle ore 00.00 del 4 febbraio 2018  e termina alle ore 23.59 del 4 marzo 2018.
•	Le sfide possono essere lanciate a partire dalle ore 23.59 del 17 febbraio 2018.
•	 le sfide non possono essere lanciate più oltre le ore 23.59 del 26 febbraio 2018

mi raccomando alla implementazione del vincolo che le sfide non possono essere lanciate prima di una certa data

mi raccomando alla implementazione del vincolo che nessuna sessione può essere registrata prima delle ore 0.0 del 4 febbraio e che le sessioni registrate non siano antecedenti a quella ora e giorno

bisognerà, inoltre,  ripulire il DB da tutte le sessioni per permettere una regolare competizione e pulita classifica

**Comment by oniram88** [comment]
ovviamente tutte le date che hai inserito con 23:59 le ho trasformate nel giorno successivo alle 00:00
dato che inserire 23:59 immagino sia un errore di logica. mancherebbero ancora 60 secondi alla mezzanotte, e non penso tu voglia inserire una cosa del genere nel regolamento.

Quindi:
•	Durata gara=        (4 febbraio 2018 T 00.00 ) < gara <  (5 marzo 2018 T 00:00) 
•	Sfide=  (18 febbraio 2018 T 00:00) < SFIDE < (  5 marzo 2018 T 00:00 - (5giorni + 2H) =27 Feb 2018 22:00:00 )

la fine della possibilità di creare sfide era stata definita come fine gara meno il numero di giorni della durata di una sfida - 2 ore aggiuntive

> che le sessioni registrate non siano antecedenti a quella ora e giorno

Questa cosa non posso controllarla io, io posso solo controllare quando inseriscono la sessione dato che non utilizziamo un sistema automatizzato di download dati di sessione (come poteva essere con strava); si potrebbe implementare qualcosa ma non è detto che sia preciso, e dovremmo mappare le informazioni da tutti i sistemi di registrazione sessioni di corsa presenti su internet ed usati dai nostri utenti.

> bisognerà, inoltre, ripulire il DB da tutte le sessioni per permettere una regolare competizione e pulita classifica

Quando mi dici che possiamo cancellare tutto lo faccio al volo.


NON mi hai inserito la data di massima iscrizione al sistema, quando è?

**Comment by ghost** [comment]
ovviamente tutte le date che hai inserito con 23:59 le ho trasformate nel giorno successivo alle 00:00
dato che inserire 23:59 immagino sia un errore di logica. mancherebbero ancora 60 secondi alla mezzanotte, e non penso tu voglia inserire una cosa del genere nel regolamento.

Quindi:
•	Durata gara= (4 febbraio 2018 T 00.00 ) < gara < (5 marzo 2018 T 00:00)
•	Sfide= (18 febbraio 2018 T 00:00) < SFIDE < ( 5 marzo 2018 T 00:00 - (5giorni + 2H) =27 Feb 2018 22:00:00 )

la fine della possibilità di creare sfide era stata definita come fine gara meno il numero di giorni della durata di una sfida - 2 ore aggiuntive

FABIO: OK perfetto!

_________________________________

che le sessioni registrate non siano antecedenti a quella ora e giorno
Questa cosa non posso controllarla io, io posso solo controllare quando inseriscono la sessione dato che non utilizziamo un sistema automatizzato di download dati di sessione (come poteva essere con strava); si potrebbe implementare qualcosa ma non è detto che sia preciso, e dovremmo mappare le informazioni da tutti i sistemi di registrazione sessioni di corsa presenti su internet ed usati dai nostri utenti.

FABIO: non è possibile inserire un controllo (da immettere all'ultimo momento prima dell'apertura del sito, per permetterci di finire i test) che la data della sessione in fase di registrazione sia nell'intervallo definito?

_______________________________________

bisognerà, inoltre, ripulire il DB da tutte le sessioni per permettere una regolare competizione e pulita classifica
Quando mi dici che possiamo cancellare tutto lo faccio al volo.

FABIO: OK perfetto!

__________________________________________________-


NON mi hai inserito la data di massima iscrizione al sistema, quando è?

FABIO: è possibile non inserire tale limite?


GRAZIEEEEEEEEE

**Comment by ghost** [comment]
piccolo lapsus

Durata gara= (4 febbraio 2018 T 00.00 ) < gara < (5 marzo 2018 T 00:00 +  2 ore)

non si sa mai gli ultimi che registrano in ritardo le ultime sessioni di gara

grazie e scusami

**Comment by oniram88** [comment]
Mi sa che per la questione sessioni ho capito male io, è già così.

**Comment by oniram88** [comment]
Per il limite di iscrizione mi hai detto tu che doveva essere presente!

**Comment by oniram88** [comment]
imposto il massimo momento di iscrizione con l'inizio della gara
