### ISSUE TITLE
Casistica di punteggi troppo differenti

### ISSUE THREAD

**Issue by oniram88** [oniram88/RunnersBikers#27]
Ho pensato che c'è una casistica in cui il 25% non è corretto come calcolo del punteggio da togliere al perdente, e come avevo anticipato sarebbe da fare il 25% sempre proporzionale a chi perde e non a chi vince:

sfidante punti: 24
sfidato punti: 100

punti in gioco: 25

sfidante perde => dovrebbe avere -1 punto come risultato nel totale dei suoi punti.

è corretto?

**Comment by ghost** [comment]
ok giusta osservazione, facciamo il 25% dei punti di chi ha il punteggio minore tra i due (sfidato sfidante)

grazie

**Comment by oniram88** [comment]
V 1.0.5
