### ISSUE TITLE
cifre decimali nel calcolo punteggio

### ISSUE THREAD

**Issue by ghost** [oniram88/RunnersBikers#29]
come detto in email qualche minuto orsono, a valle del fallimento proclamazione vincitore sfida di test,
è necessario considerare nel punteggio le cifre decimali

oltre a quanto appena scritto

controllare, a questo punto, che la sfida venga assegnata sulla base di chi ha ottenuto realmente il punteggio di sessione più alto

grazie

**Comment by oniram88** [comment]
quante cifre decimali?
devono essere visualizzate anche nella classifica i decimali?
devo arrotondare o troncare al N decimale?

**Comment by ghost** [comment]
io proporrei, per tutte le operazioni di gara, utilizzare sino alla terza cifra decimale.

tutte le operazioni di gara, vuol dire sia visualizzazione nella classifica che scelta del vincitore nelle sfide.

arrotondiamo alla quarta, ammesso che sia necessario viste le due frasi precedenti

grazie
