### ISSUE TITLE
menuù sfida per utenti normali

### ISSUE THREAD

**Issue by ghost** [oniram88/RunnersBikers#30]
nel menù sfida, con utenti normali, continuo a vedere una schermata vuota.

ricordo quanto ci siamo detti per telefono a tale proposito.

gli utenti arbitri debbono poter vedere tutte le sessioni e possono modificarle, almeno sino a quando non sono state approvate / validate.

gli utenti standard devono solo poter vedere la lista delle sfide con i vincitori. (senza poter modificare nulla)

grazie
fabio

**Comment by oniram88** [comment]
come potrai notare nella issue chiusa #20 ho segnato che la versione in cui sarà presente tale correzione è la 1.0.6
in questo momento è online la 1.0.5
conseguentemente devi aspettare.

**Comment by oniram88** [comment]
duplicate of #20
