### ISSUE TITLE
stesso punteggio

### ISSUE THREAD

**Issue by oniram88** [oniram88/RunnersBikers#31]
per quanto remoto possa essere, cosa accade se gli utenti raggiungono lo stesso punteggio? chi vince?

**Comment by ghost** [comment]
che ci sia lo stesso punteggio nelle sfide sino alla terza cifra decimale mi sembra assurdo, ma guarda cquello che sono stato capace (inconsapevolmente) di fare ieri..

io dire che, se sino alla terza cifra, il punteggio è lo stesso la sfida sarà pari e patta. il che vuol dire che nessuno vincerà e nessuno guadagnerà nulla.

questo, caso, immagino apra un film dal punto di vista della implementazione per te

grazieeee

**Comment by oniram88** [comment]
no, basta sapere come si deve comportare il programma.

**Comment by ghost** [comment]
per questa hai bisogno del mio aiuto?

**Comment by oniram88** [comment]
perfetto, fatto anche questa, si comporta come una normale sfida, quando un giudice approva la sfida viene inviata questa mail:


> Ti comunichiamo che la sfida non ha avuto nessun vincitore in quanto il risultato è stato uguale
> 
> le sessioni di sfida sono state:
> 
> pluto paperlopoli Sessione 63.125
> 
> marino bonetti Sessione 63.125
> 
> Da ora potete nuovamente sfidare un nuovo concorrente, secondo le regole del torneo.
> 
> Grazie per l’entusiasmo che dimostri partecipando al torneo,

se hai qualche modifica da fare al testo fammi sapere
