### ISSUE TITLE
nel menù sfide, un utente non amministratore può inserire delle note a ciascuna sfida

### ISSUE THREAD

**Issue by ghost** [oniram88/RunnersBikers#34]
non so che senso abbia, ma se non è strettamente necessario potremmo disabilitare tale funzione

grazie
fabio

**Comment by oniram88** [comment]
Teoricamente dovrebbe avere solo L’admin questa capacità  come mi avevi chiesto. Controllo

**Comment by ghost** [comment]
ok grazie
