### ISSUE TITLE
nome competizione nella pagina di iscrizione / login

### ISSUE THREAD

**Issue by ghost** [oniram88/RunnersBikers#35]
oltre al logo, che hai già inserito, si può inserire anche il nome competizione?

grazie
fabio

**Comment by oniram88** [comment]
Quale none? Dove? Sotto al logo?
E poi dentro serve accanto al logo o no?

**Comment by ghost** [comment]
I torneo next challenge per runner.. SOLO nella pagina iniziale sotto al logo

non ha senso inserirla altrove

grazie
