### ISSUE TITLE
al PRIMO LOGIN di ciascun nuovo utente si viene reindirizzati ad una pagina vuota

### ISSUE THREAD

**Issue by ghost** [oniram88/RunnersBikers#36]
in cui non si può fare nulla

per sbloccare la situazione, bisogna  re immettere l'indirizzo del sito,

ma se mi sono loggato non capisco perchè succeda questa cosa

grazie
fabio

**Comment by ghost** [comment]
ho provato a cambiare browser e la issue si ripete

**Comment by oniram88** [comment]
era un problema di cloudflare - corretto
