### ISSUE TITLE
dopo aver inserito una nuova sessione si viene reindirizzi al menù sfide

### ISSUE THREAD

**Issue by ghost** [oniram88/RunnersBikers#38]
è possibile fare il redirect verso il menù lista sessioni?

grazie
fabio

**Comment by oniram88** [comment]
Dipende sempre da dove arrivi. Ma se di default si vuole che dalla generazione sessione si torna alla lista sessioni non è un problema

**Comment by ghost** [comment]
si sarebbe fantastico, dopo aver inserito una sessione si va alla lista sessioni

grazie
