### ISSUE TITLE
Referal

### ISSUE THREAD

**Issue by oniram88** [oniram88/RunnersBikers#43]
inserire campo in ogni utente per il referal in modo che se il figlio dopo li N (2) sessioni darà X (30) punti aggiuntivi al padre.

Preparare sistema di importazione da CSV per automatizzare caricamento referal/child
Tracciato Record:
email figlio | email padre

**Comment by oniram88** [comment]
In questo momento semplifichiamo ed inseriamo un solo campo nell’utente, che vada a identificare i suoi punti guadagnati come referal, questi punti poi li visualizziamo da qualche parte e fanno parte del portfolio di punti da poter utilizzare comunque anche nelle sfide

**Comment by oniram88** [comment]
@fbarnaba  ho messo i punti referal nell'header dell'applicazione, e già che cero anche i punti totali propri dell'utente.

**Comment by ghost** [comment]
perdona l'ignoranza. ma cosa vuol dire: ho messo i punti referal
nell'header dell'applicazione, e già che cero anche i punti totali propri
dell'utente.

dovrò comunicare a te i punti da aggiungere o saremo autonomi?

grazie e scusa per la rottura di pall....

buon pranzo

fabio


2018-05-25 14:18 GMT+02:00 Marino Bonetti <notifications@github.com>:
