### ISSUE TITLE
Nelle sfide aggiungere ‘ora italiana’

### ISSUE THREAD

**Issue by oniram88** [oniram88/RunnersBikers#47]
inserire nella schermata sfide l'orario specificando il fusorario ed email

**Comment by oniram88** [comment]
@fbarnaba  non mi ricordo per cosa avevamo detto di visualizzare la mail.

**Comment by ghost** [comment]
nel menù sfide

nella intestazione di colonna che se non erro si chiama 'data fine sfida'
scrivere 'data fine sfida (ora italia)'

2018-05-23 13:52 GMT+02:00 Marino Bonetti <notifications@github.com>:

**Comment by oniram88** [comment]
ok, ma mi ero segnato anche "ed email"
ma non capisco perchè

**Comment by ghost** [comment]
perchè forse nel testo della email che viene mandata ad avvio sfida,
nell'orario di fine sfida va specificat 'ora italiana'

2018-05-23 13:55 GMT+02:00 Marino Bonetti <notifications@github.com>:

**Comment by oniram88** [comment]
ah...ok, ora torna, grazie!!!!

**Comment by ghost** [comment]
a te

2018-05-23 13:57 GMT+02:00 Marino Bonetti <notifications@github.com>:
