### ISSUE TITLE
pagina di inserimento sessioni

### ISSUE THREAD

**Issue by ghost** [oniram88/RunnersBikers#6]
accando alla descrizione dei campi (label) va inserito il formato dei dati da inserire, per facilitare ulteriormente l'utente che dovrà inserire i dati
grazie

**Comment by oniram88** [comment]
inserisci a sx anche il formato, e nell'errore del formato del pace una notifica di come deve essere il formato

**Comment by oniram88** [comment]
versione 1.0.3
