### ISSUE TITLE
sfide

### ISSUE THREAD

**Issue by ghost** [oniram88/RunnersBikers#7]
sto provando ad effettuare il test delle sfide, ma quando seleziono il menù sfide compare una schermata vuota

**Comment by oniram88** [comment]
non sono presenti sfide, pensavo di visualizzare li tutte le sfide dove un'utente è legato ad una di quelle sfide, e per un amministratore vederle tutte.

**Comment by ghost** [comment]
Non capisco

Allora da dove lancio le sfide all
Interno del
Programma?

Il giorno mar 26 dic 2017 alle 15:56 Marino Bonetti <
notifications@github.com> ha scritto:

**Comment by oniram88** [comment]
utente normale vede tutte le sfide, ma non può modificare nulla.

**Comment by oniram88** [comment]
Mi hai chiuso la issue ma non era fatta, mi ero appunto segnato quello che poi ieri l’altro giorno mi hai riscritto in un’altra issue.

**Comment by oniram88** [comment]
V 1.0.6
