### ISSUE TITLE
calcolo punteggio

### ISSUE THREAD

**Issue by ghost** [oniram88/RunnersBikers#8]
non riesco a capire.

a fronte di 14km , ritmo medio 6:43, dislivello positivo 56 è venuto fuori un punteggio 14000

ricordo che

    P =    100 * ( D + d / 100 ) / r ²

con   P = punteggio sessione
        D = distanza in km
        d = dislivello positivo in m
        r = ritmo medio in min/km (es. 5,3 è 5'30")

**Comment by oniram88** [comment]
Effettivamente dovrebbe uscire 280

Il calcolo sarebbe così tradotto:
100*(14+(56/100))/((5*60+30)/60)

comunque
5:30 di passo non sono 5,30 minuti, ma sono 5,5!!!!

**Comment by oniram88** [comment]
scusa.....264 è il punteggio

**Comment by oniram88** [comment]
ok, risolto, il problema era nelle virgole troncate, e nella trasposizione errata da formato tempo a decimale
ab44789a90908143dfce64fb9ad8dd0da16bdc45
